routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('', function () {
        return view('admin.index');
    });
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::get('post/active', 'PostController@active')->name('admin.post.active');
    Route::resource('post', 'PostController', ['as' => 'admin']);
    Route::get('product/active', 'ProductController@active')->name('admin.product.active');
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('contact', 'ContactController', ['as' => 'admin']);
    Route::get('information/', 'InformationController@index')->name('admin.information.index');
    Route::put('information/update/{id}', 'InformationController@update')->name('admin.information.update');
    Route::get('user/active', 'UserController@active')->name('admin.user.active');
    Route::resource('user', 'UserController', ['as' => 'admin']);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $fillable = [
        'id',
        'name',
        'image',
        'parent_id',
    ];

    public function products()
    {
        return $this->hasMany('App\Models\Product');
    }

    public function parent()
    {
        return $this->belongsTo('App\Models\Category', 'parent_id');
    }

    public function children()
    {
        return $this->hasMany('App\Models\Category', 'parent_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::whereNull('parent_id')
                                ->with('children')
                                ->get();
        return view('admin.category.index', compact('categories'));

    }

    public function create()
    {
        $categories = Category::all();
        return view('admin.category.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $category = new Category;
        $category->name = $request->name;
        $category->slug = Str::slug($request->name);
        $category->parent_id = $request->parent_id;

        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $category->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $category->image = $filename;
        } 
        $category->save();

        return redirect()->route('admin.category.index')->with('success', 'Create category successfully');
    }

    public function show($id)
    {
    }
    
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        $categories = Category::all();
        return view('admin.category.edit', compact('category', 'categories'));
      
    }

    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->slug = Str::slug($request->name);
        $category->parent_id = $request->parent_id;

        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $category->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $category->image = $filename;
        } 
        $category->save();

        return redirect()->route('admin.category.index')->with('success', 'Update category successfully');
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $path = public_path('upload/images/');
        $file_old = $path . $category->image;
        if(File::exists($file_old)) {
            File::delete($file_old); 
        }
        $category->delete();
        return redirect()->route('admin.category.index')->with('success', 'Delete category successfully');
    }
}

resources/views/admin/category/child_category.blade.php
<li class="mb-3">
    <form class="" action="{{ route('admin.category.destroy', $child_category->id)}}" method="post">
        <div class="sub-category">
            <span class="mr-2">{{ $child_category->name }}</span>
            <img style="width: 100px; object-fit: cover" class="" src="{{ asset('upload/images/'. $child_category->image)}}" alt="">
            @csrf
            @method('DELETE')
            <a class="btn btn-danger" href="" data-toggle="modal" data-target="#modelId-{{ $child_category->id}}">Delete</a>
            <a class="btn btn-primary" href="{{ route('admin.category.edit', $child_category->id)}}" role="button">Edit</a>
            <!-- Modal -->
            <div class="modal fade" id="modelId-{{ $child_category->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete category</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                        <div class="modal-body">
                            Are you sure?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</li>
@if ($child_category->children)
    <ul>
        @foreach ($child_category->children as $childCategory)
            @include('admin.category.child_category', ['child_category' => $childCategory])
        @endforeach
    </ul>
@endif

resources/views/admin/category/create.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Category</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Add Category</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.category.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Name</label>
                            <input type="text" name="name" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                            <label for="">Parent</label>
                            <select class="custom-select" name="parent_id" id="">
                                <option selected value="{{ null}}">Prarent category</option>
                                @foreach ($categories as $item)
                                    <option value="{{ $item->id}}">{{ $item->name}}</option>
                                @endforeach
                            </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="">Image</label>
                      <input type="file" class="form-control-file" name="image">
                    </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Category</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Category</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.category.update', $category->id)}}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Name</label>
                            <input type="text" name="name" class="form-control form-control-user" value="{{ $category->name}}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                            <label for="">Parent</label>
                            <select class="custom-select" name="parent_id" id="" >
                                <option  value="{{ null}}">Prarent category</option>
                                @foreach ($categories as $item)
                                    <option {{ $item->id == $category->id ? 'selected' : ''}} value="{{ $item->id}}">{{ $item->name}}</option>
                                @endforeach
                            </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <label for="">Image</label>
                      <input type="file" class="form-control-file" name="image">
                      <img class="mt-2" width="120px" src="{{ asset('upload/images/'. $item->image)}}" alt="">
                    </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/category/index.blade.php
@extends('templates.admin.master') @section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Category</h1>
    <a class="btn btn-success mb-2"  href="{{ route('admin.category.create') }}">Add category</a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All Category</h6>
            @include('errors.success')
        </div>
        <div class="card-body">
                <ul>
                    @foreach ($categories as $category)
                        <li class="mb-3">
                            <form class="" action="{{ route('admin.category.destroy', $category->id)}}" method="post">
                                <div class="sub-category">
                                    <span class="mr-2">{{ $category->name }}</span>
                                    <img style="width: 100px; object-fit: cover" class="" src="{{ asset('upload/images/'. $category->image)}}" alt="">
                                    @csrf
                                    @method('DELETE')
                                    <a class="btn btn-danger" href="" data-toggle="modal" data-target="#modelId-{{ $category->id}}">Delete</a>
                                    <a class="btn btn-primary" href="{{ route('admin.category.edit', $category->id)}}" role="button">Edit</a>
                                    <!-- Modal -->
                                    <div class="modal fade" id="modelId-{{ $category->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Delete category</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </li>
                       
                        <ul>
                            @foreach ($category->children as $childCategory)
                                @include('admin.category.child_category', ['child_category' => $childCategory])
                            @endforeach
                        </ul>
                    @endforeach
            	</ul>
        </div>
    </div>
</div>
@endsection