routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('', function () {
        return view('admin.index');
    });
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::get('post/active', 'PostController@active')->name('admin.post.active');
    Route::resource('post', 'PostController', ['as' => 'admin']);
    Route::get('product/active', 'ProductController@active')->name('admin.product.active');
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('contact', 'ContactController', ['as' => 'admin']);
    Route::get('information/', 'InformationController@index')->name('admin.information.index');
    Route::put('information/update/{id}', 'InformationController@update')->name('admin.information.update');
    Route::get('user/active', 'UserController@active')->name('admin.user.active');
    Route::resource('user', 'UserController', ['as' => 'admin']);
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'posts';
    protected $fillable = [
        'title',
        'slug',
        'image',
        'description',
        'content',
        'keyword',
        'active'
    ];
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Post;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class PostController extends Controller
{
    public function index()
    {
        $posts = Post::all();
        return view('admin.post.index', compact('posts'));
    }

    public function create()
    {
        return view('admin.post.create');
    }

    public function store(Request $request)
    {
        $post = new Post;
        $post->title = $request->title;
        $post->slug = Str::slug($request->name);
        $post->description = $request->description;
        $post->content = $request->content;
        $post->keyword = $request->keyword;
        $post->active = 1;

        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $post->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $post->image = $filename;
        } 
        $post->save();

        return redirect()->route('admin.post.index')->with('success', 'Create post successfully');
    }

    public function show($id)
    {
    }
    
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('admin.post.edit', compact('post'));
      
    }

    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $post->title = $request->title;
        $post->slug = Str::slug($request->name);
        $post->description = $request->description;
        $post->content = $request->content;
        $post->keyword = $request->keyword;

        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $post->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $post->image = $filename;
        } 
        $post->save();

        return redirect()->route('admin.post.index')->with('success', 'Update post successfully');
    }

    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        $path = public_path('upload/images/');
        $file_old = $path . $post->image;
        if(File::exists($file_old)) {
            File::delete($file_old); 
        }
        $post->delete();
        return redirect()->route('admin.post.index')->with('success', 'Delete post successfully');
    }

    public function active(Request $request)
    {
        $id = $request->id;
        $product = Post::findOrFail($id);
        if ($product->active == 0) {
            $product->active = 1;
            $product->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fas fa-check text-success"></i> </a>';
        } else {
            $product->active = 0;
            $product->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fas fa-times text-danger"></i> </a>';
        }
    }
}

resources/views/admin/post/create.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">post</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Add post</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.post.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Title</label>
                            <input type="text" name="title" class="form-control form-control-user"  >
                            <p class="text-danger">{{ $errors->first('title') }}</p>
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Description</label>
                            <input type="text" name="description" class="form-control form-control-user"  >
                            <p class="text-danger">{{ $errors->first('description') }}</p>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="" class=" form-control-label">Content</label>
                      <textarea name="content" class="form-control " id="editor1">{!! old('content')!!}</textarea>
                      @if ($errors->has('content'))
                          <p class="text-danger">{{ $errors->first('content') }}</p>
                      @endif
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">keyword</label>
                            <input type="text" name="keyword" class="form-control form-control-user"  >
                            <p class="text-danger">{{ $errors->first('keyword') }}</p>
                      </div>
                    </div>
                    
                    <div class="form-group">
                      <label for="">Image</label>
                      <input type="file" class="form-control-file" name="image">
                      <p class="text-danger">{{ $errors->first('image') }}</p>
                    </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };
</script>
<script>
  CKEDITOR.replace('editor1', options);
</script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
$('textarea.editor1').ckeditor(options);
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      if (window.File && window.FileList && window.FileReader) {
        $("#files").on("change", function(e) {
          var files = e.target.files,
            filesLength = files.length;
          for (var i = 0; i < filesLength; i++) {
            var f = files[i]
            var fileReader = new FileReader();
            fileReader.onload = (function(e) {
              var file = e.target;
              $("<span class=\"pip\">" +
                "<img class=\"imageThumb\" width='100px' src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" +
                "<br/><span class=\"remove\">Remove image</span>" +
                "</span>").insertAfter("#files");
              $(".remove").click(function(){
                $(this).parent(".pip").remove();
              });
            });
            fileReader.readAsDataURL(f);
          }
        });
      } else {
        alert("Your browser doesn't support to File API")
      }
    });
</script>
@endsection

resources/views/admin/post/edit.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">post</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Update post</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.post.update', $post->id)}}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Title</label>
                            <input type="text" name="title" class="form-control form-control-user"  value="{{ $post->title}}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Description</label>
                            <input type="text" name="description" class="form-control form-control-user" value="{{ $post->description}}" >
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">content</label>
                            <input type="text" name="content" class="form-control form-control-user" value="{{ $post->content}}" >
                      </div>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">keyword</label>
                            <input type="text" name="keyword" class="form-control form-control-user"  value="{{ $post->keyword}}">
                      </div>
                    </div>
                    
                    <div class="form-group">
                      <label for="">Image</label>
                      <input type="file" class="form-control-file" name="image">
                      <img width="120px" class="mt-2" src="{{ asset('upload/images/'. $post->image)}}" alt="">
                    </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/post/index.blade.php
@extends('templates.admin.master') @section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Post</h1>
    <a class="btn btn-success mb-2"  href="{{ route('admin.post.create') }}">Add Post</a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All Post</h6>
            @include('errors.success')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0"
                                role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-sort="ascending" aria-label="Name: activate to sort
                                            column descending" style="width: 20px;">
                                            Id
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Image
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Position:
                                            activate to sort column ascending" style="width: 246px;">
                                            Title
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Office:
                                            activate to sort column ascending" style="width: 50px;">
                                            Description
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Key word
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Active
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                        colspan="1" aria-label="Age:
                                        activate to sort column ascending" style="width: 90px;">
                                        Actions
                                    </th>
                                   
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($posts as $key => $item)
                                        <tr role="row" class="{{ $key %2 == 0 ? 'odd' : 'even'}}">
                                            <td class="sorting_1">{{ $item->id}}</td>
                                            <td><img style="width: 70px" src="{{ asset('upload/images/'. $item->image)}}" alt=""></td>
                                            <td>{{ $item->title}}</td>
                                            <td>{{ $item->description}}</td>
                                            <td>{{ $item->keyword}}</td>
                                            <td id="active-{{ $item->id }}"> 
                                                @if ($item->active == 1)
                                                  <a href="javascript:void(0)" onclick="getActive({{$item->id}})" style="cursor: pointer"><i class="fas fa-check text-success"></i> </a>
                                                @else
                                                  <a href="javascript:void(0)" onclick="getActive({{$item->id}})" style="cursor: pointer"><i class="fas fa-times text-danger"></i></a>
                                                @endif
                                              </td>
                                            <td>
                                                <form action="{{ route('admin.post.destroy', $item->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a class="btn btn-danger" href="" data-toggle="modal" data-target="#modelId-{{ $item->id}}">Delete</a>
                                                    <a class="btn btn-primary" href="{{ route('admin.post.edit', $item->id)}}" role="button">Edit</a>
                                                    <!-- Modal -->
                                                    <div class="modal fade" id="modelId-{{ $item->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title">Delete post</h5>
                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    Are you sure?
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                                
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    function getActive(id){
       $.ajax({
         url: "{{route('admin.post.active')}}",
         type: 'GET',
         cache: false,
         data: {
               id: id,
           },
         success: function(data){
           console.log('success')
           $('#active-'+id).html(data);
         },
         error: function() {
          alert("Có lỗi");
        }
      });
       return false;
     }
</script>
@endsection