routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('', function () {
        return view('admin.index');
    });
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::get('post/active', 'PostController@active')->name('admin.post.active');
    Route::resource('post', 'PostController', ['as' => 'admin']);
    Route::get('product/active', 'ProductController@active')->name('admin.product.active');
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('contact', 'ContactController', ['as' => 'admin']);
    Route::get('information/', 'InformationController@index')->name('admin.information.index');
    Route::put('information/update/{id}', 'InformationController@update')->name('admin.information.update');
    Route::get('user/active', 'UserController@active')->name('admin.user.active');
    Route::resource('user', 'UserController', ['as' => 'admin']);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    protected $fillable = [
        'category_id',
        'name',
        'slug',
        'image',
        'price',
        'promotion_price',
        'quantity',
        'sku',
        'description',
        'content',
        'active',
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Carbon\Carbon;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        $products = Product::OrderBy('id', 'desc')->paginate(50);
        return view('admin.product.index', compact('products'));
    }
    
    public function create()
    {
        $categories = Category::all();
        return view('admin.product.create', compact('categories'));
    }
   
    public function store(Request $request)
    {   
        $product = new Product();
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:products',
            'sku' => 'required',
            'description' => 'required',
            'content'=>'required',
            'quantity'=>'required',
            'price' => 'required',
            'promotion_price' => 'required',
            'image' => 'required',
        ],[
            'name.required' => 'Bạn cần nhập tên sản phẩm',
            'sku.required' => 'Bạn cần nhập mã sản phẩm',
            'description.required' => 'Bạn cần nhập mô tả',
            'content.required' => 'Bạn cần nhập nội dung của sản phẩm',
            'price.required' => 'Bạn cần nhập giá của sản phẩm',
            'quantity.required' => 'Bạn cần nhập só lượng của sản phẩm',
            'promotion_price.required' => 'Bạn cần nhập giá khuyến mãi của sản phẩm',
            'image.required' => 'Bạn cần tải ảnh lên',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        } 

        $product->category_id  = $request->category_id; 
        $product->name  = $request->name; 
        $product->sku  = $request->sku; 
        $product->slug  = Str::slug($request->name); 
        $product->description  = $request->description; 
        $product->content =$request->content;
        $product->price  = $request->price; 
        $product->promotion_price  = $request->promotion_price; 
        $product->created_at = Carbon::now('Asia/Ho_Chi_Minh');
        $product->updated_at = Carbon::now('Asia/Ho_Chi_Minh');

        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $product->image = $filename;
        } 
        $product->save();
        return redirect()->route('admin.product.index')->with('success', 'Thêm sản phẩm thành công!');
    }

    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::all();
        return view('admin.product.edit', compact('product', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);
        $validator = Validator::make($request->all(), [
            'name' => 'unique:products,name,'. $id,
        ],[
            'name.unique' => 'Tên sản phẩm đã tồn tại'
        ]);
            
        if ($validator->fails()) {
            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            } 
        }

        $product->category_id  = $request->category_id; 
        $product->name  = $request->name; 
        $product->sku  = $request->sku; 
        $product->slug  = Str::slug($request->name); 
        $product->description  = $request->description; 
        $product->content =$request->content;
        $product->price  = $request->price; 
        $product->promotion_price  = $request->promotion_price; 
        $product->created_at = Carbon::now('Asia/Ho_Chi_Minh');
        $product->updated_at = Carbon::now('Asia/Ho_Chi_Minh');
        
        if ($request->file('image') != '') {
            $path = public_path('upload/images/');
            $file_old = $path . $product->image;
            if(File::exists($file_old)) {
                File::delete($file_old); 
            }
            
            $file = $request->file('image');
            $filename = time().$file->getClientOriginalName();
            $file->move('./upload/images/', $filename);
            $product->image = $filename;
        } 
        
        $product->save();
        return redirect()->route('admin.product.index')->with('success', 'Cập nhật sản phẩm thành công!');
    }
    
    public function destroy(Request $request,$id)
    {
        $product = Product::findOrFail($id);
        $path = public_path('upload/images/');
        $file_old = $path . $product->image;
        if(File::exists($file_old)) {
            File::delete($file_old); 
        }
        $product->delete();
        return redirect()->route('admin.product.index')->with('success', 'Xóa sản phẩm thành công');
    }

    public function active(Request $request)
    {
        $id = $request->id;
        $product = Product::findOrFail($id);
        if ($product->active == 0) {
            $product->active = 1;
            $product->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fas fa-check text-success"></i> </a>';
        } else {
            $product->active = 0;
            $product->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fas fa-times text-danger"></i> </a>';
        }
    }
}

resources/views/admin/product/create.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Product</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Add Product</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.product.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                      <label for="">Category</label>
                      <select class="form-control" name="category_id" id="">
                          @foreach ($categories as $item)
                              <option value="{{ $item->id}}">{{ $item->name}}</option>
                          @endforeach
                      </select>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Name</label>
                            <input type="text" name="name" class="form-control form-control-user">
                            <p class="text-danger">{{ $errors->first('name') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Price</label>
                            <input type="text" name="price" class="form-control form-control-user">
                            <p class="text-danger">{{ $errors->first('price') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Promotion price</label>
                            <input type="text" name="promotion_price" class="form-control form-control-user">
                            <p class="text-danger">{{ $errors->first('promotion_price') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Quantity</label>
                            <input type="text" name="quantity" class="form-control form-control-user">
                            <p class="text-danger">{{ $errors->first('quantity') }}</p>
                      </div>
                    </div>

                    
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Sku</label>
                            <input type="text" name="sku" class="form-control form-control-user">
                            <p class="text-danger">{{ $errors->first('sku') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Description</label>
                            <input type="text" name="description" class="form-control form-control-user">
                            <p class="text-danger">{{ $errors->first('description') }}</p>
                      </div>
                    </div>

                     <div class="form-group">
                      <label for="" class=" form-control-label">Content</label>
                      <textarea name="content" class="form-control " id="editor1">{!! old('content')!!}</textarea>
                      <p class="text-danger">{{ $errors->first('content') }}</p>
                    </div>
                    <div class="form-group">
                      <label for="">Image</label>
                      <input type="file" class="form-control-file" name="image">
                      <span class="text-danger">{{ $errors->first('image') }}</span>
                    </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };
</script>
<script>
  CKEDITOR.replace('editor1', options);
</script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
$('textarea.editor1').ckeditor(options);
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      if (window.File && window.FileList && window.FileReader) {
        $("#files").on("change", function(e) {
          var files = e.target.files,
            filesLength = files.length;
          for (var i = 0; i < filesLength; i++) {
            var f = files[i]
            var fileReader = new FileReader();
            fileReader.onload = (function(e) {
              var file = e.target;
              $("<span class=\"pip\">" +
                "<img class=\"imageThumb\" width='100px' src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" +
                "<br/><span class=\"remove\">Remove image</span>" +
                "</span>").insertAfter("#files");
              $(".remove").click(function(){
                $(this).parent(".pip").remove();
              });
              
              
            });
            fileReader.readAsDataURL(f);
          }
        });
      } else {
        alert("Your browser doesn't support to File API")
      }
    });
</script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Product</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Product</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.product.update', $product->id)}}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                      <label for="">Category</label>
                      <select class="form-control" name="category_id" id="">
                          @foreach ($categories as $item)
                              <option value="{{ $item->id}}">{{ $item->name}}</option>
                          @endforeach
                      </select>
                    </div>
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Name</label>
                            <input type="text" name="name" class="form-control form-control-user" value="{{ $product->name}}">
                            <p class="text-danger">{{ $errors->first('name') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Price</label>
                            <input type="text" name="price" class="form-control form-control-user" value="{{ $product->price}}">
                            <p class="text-danger">{{ $errors->first('price') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Promotion price</label>
                            <input type="text" name="promotion_price" class="form-control form-control-user" value="{{ $product->promotion_price}}">
                            <p class="text-danger">{{ $errors->first('promotion_price') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Quantity</label>
                            <input type="text" name="quantity" class="form-control form-control-user" value="{{ $product->quantity}}">
                            <p class="text-danger">{{ $errors->first('quantity') }}</p>
                      </div>
                    </div>

                    
                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Sku</label>
                            <input type="text" name="sku" class="form-control form-control-user" value="{{ $product->sku}}">
                            <p class="text-danger">{{ $errors->first('sku') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-12">
                          <label for="">Description</label>
                            <input type="text" name="description" class="form-control form-control-user" value="{{ $product->description}}">
                            <p class="text-danger">{{ $errors->first('description') }}</p>
                      </div>
                    </div>

                     <div class="form-group">
                      <label for="" class=" form-control-label">Content</label>
                      <textarea name="content" class="form-control " id="editor1">{!! $product->content !!}</textarea>
                      <p class="text-danger">{{ $errors->first('content') }}</p>
                    </div>
                    <div class="form-group">
                      <label for="">Image</label>
                      <input type="file" class="form-control-file" name="image">
                      <span class="text-danger">{{ $errors->first('image') }}</span>
                      <img class="mt-3" width="150px" src="{{ asset('upload/imgages/' . $product->image)}}" alt="">
                    </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };
</script>
<script>
  CKEDITOR.replace('editor1', options);
</script>
<script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
<script>
$('textarea.editor1').ckeditor(options);
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      if (window.File && window.FileList && window.FileReader) {
        $("#files").on("change", function(e) {
          var files = e.target.files,
            filesLength = files.length;
          for (var i = 0; i < filesLength; i++) {
            var f = files[i]
            var fileReader = new FileReader();
            fileReader.onload = (function(e) {
              var file = e.target;
              $("<span class=\"pip\">" +
                "<img class=\"imageThumb\" width='100px' src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" +
                "<br/><span class=\"remove\">Remove image</span>" +
                "</span>").insertAfter("#files");
              $(".remove").click(function(){
                $(this).parent(".pip").remove();
              });
              
              
            });
            fileReader.readAsDataURL(f);
          }
        });
      } else {
        alert("Your browser doesn't support to File API")
      }
    });
</script>
@endsection

resources/views/admin/product/index.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Product</h1>
    <a class="btn btn-success mb-2"  href="{{ route('admin.product.create') }}">Add Product</a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All Product</h6>
            @include('errors.success')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0"
                                role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-sort="ascending" aria-label="Name: activate to sort
                                            column descending" style="width: 20px;">
                                            Id
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Image
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Position:
                                            activate to sort column ascending" style="width: 170px;">
                                            Name
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Office:
                                            activate to sort column ascending" style="width: 50px;">
                                            Slug
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Category
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Price
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Active
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 90px;">
                                            Actions
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($products as $key => $item)
                                        <tr role="row" class="{{ $key %2 == 0 ? 'odd' : 'even'}}">
                                            <td class="sorting_1">{{ $item->id}}</td>
                                            <td><img style="width: 70px" src="{{ asset('upload/images/'. $item->image)}}" alt=""></td>
                                            <td>{{ $item->name}}</td>
                                            <td>{{ $item->slug}}</td>
                                            <td>{{ $item->category->name}}</td>
                                            <td>{{ number_format($item->price)}} đ</td>
                                            <td id="active-{{ $item->id }}"> 
                                                @if ($item->active == 1)
                                                  <a href="javascript:void(0)" onclick="getActive({{$item->id}})" style="cursor: pointer"><i class="fas fa-check text-success"></i> </a>
                                                @else
                                                  <a href="javascript:void(0)" onclick="getActive({{$item->id}})" style="cursor: pointer"><i class="fas fa-times text-danger"></i></a>
                                                @endif
                                              </td>
                                            <td>
                                                <form action="{{ route('admin.product.destroy', $item->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a class="btn btn-danger" href="" data-toggle="modal" data-target="#modelId-{{ $item->id}}">Delete</a>
                                                    <a class="btn btn-primary" href="{{ route('admin.product.edit', $item->id)}}" role="button">Edit</a>
                                                    <!-- Modal -->
                                                    <div class="modal fade" id="modelId-{{ $item->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title">Delete category</h5>
                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    Are you sure?
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                                
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    function getActive(id){
       $.ajax({
         url: "{{route('admin.product.active')}}",
         type: 'GET',
         cache: false,
         data: {
               id: id,
           },
         success: function(data){
           console.log('success')
           $('#active-'+id).html(data);
         },
         error: function() {
          alert("Có lỗi");
        }
      });
       return false;
     }
</script>
@endsection