routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('', function () {
        return view('admin.index');
    });
    Route::resource('category', 'CategoryController', ['as' => 'admin']);
    Route::get('post/active', 'PostController@active')->name('admin.post.active');
    Route::resource('post', 'PostController', ['as' => 'admin']);
    Route::get('product/active', 'ProductController@active')->name('admin.product.active');
    Route::resource('product', 'ProductController', ['as' => 'admin']);
    Route::resource('contact', 'ContactController', ['as' => 'admin']);
    Route::get('information/', 'InformationController@index')->name('admin.information.index');
    Route::put('information/update/{id}', 'InformationController@update')->name('admin.information.update');
    Route::get('user/active', 'UserController@active')->name('admin.user.active');
    Route::resource('user', 'UserController', ['as' => 'admin']);
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function index()
    {
        $users = User::paginate(10);
        return view('admin.user.index', compact('users'));
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|min:6',
            'email' => 'required|email',
            'password' => 'required',
            're_password' => 'same:password|min:6',
            'role' => 'required',
            'active' => 'required',
        ],[
            'name.required' => 'Bạn cần phải nhập tên người dùng',
            'email.required' => 'Bạn cần phải nhập email',
            'password.required' => 'Bạn cần phải nhập mật khẩu',
            're_password.same' => 'Mật khẩu xác nhận cần giống với mật khẩu',
            'role.required' => 'Bạn cần phải chọn role',
            'active.required' => 'Bạn cần phải chọn active',
        ]);
            
        if ($validator->fails()) {
            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            } 
        }
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->role = $request->role;
        $user->active = $request->active;

        $user->save();
        return redirect()->route('admin.user.index')->with('success', 'Thêm người dùng thành công');
    }

    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.user.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|min:6',
            'email' => 'required|email',
            'role' => 'required',
            'active' => 'required',
        ],[
            'name.required' => 'Bạn cần phải nhập tên người dùng',
            'email.required' => 'Bạn cần phải nhập email',
            'role.required' => 'Bạn cần phải chọn role',
            'active.required' => 'Bạn cần phải chọn active',
        ]);
            
        if ($validator->fails()) {
            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            } 
        }
        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->active = $request->active;

        $user->save();
        return redirect()->route('admin.user.index')->with('success', 'Cập nhật người dùng thành công');
    }
    public function destroy(Request $request,$id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('admin.user.index')->with('success', 'Xóa người dùng thành công');
    }

    public function active(Request $request)
    {
        $id = $request->id;
        $user = User::findOrFail($id);
        if ($user->active == 0) {
            $user->active = 1;
            $user->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fas fa-check text-success"></i> </a>';
        } else {
            $user->active = 0;
            $user->save();
            return '<a href="javascript:void(0)" onclick="getActive('.$id.')" style="cursor: pointer"><i class="fas fa-times text-danger"></i> </a>';
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">User</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Add User</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.user.store')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                      <div class="col-sm-12 mb-3 ">
                          <label for="">Name</label>
                            <input type="text" name="name" class="form-control form-control-user" >
                            <p class="text-danger">{{ $errors->first('name') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-12 mb-3 ">
                            <label for="">Email</label>
                                <input type="text" name="email" class="form-control form-control-user" >
                                <p class="text-danger">{{ $errors->first('email') }}</p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-12 mb-3 ">
                            <label for="">Password</label>
                                <input type="text" name="password" class="form-control form-control-user" >
                                <p class="text-danger">{{ $errors->first('password') }}</p>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 mb-3 ">
                            <label for="">Confirm password</label>
                                <input type="text" name="re_passwrod" class="form-control form-control-user" >
                                <p class="text-danger">{{ $errors->first('re_password') }}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="">Role</label>
                        <select class="custom-select" name="role">
                            <option value="">-----</option>
                            <option value="0">User</option>
                            <option value="1">Admin</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('role') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Active</label>
                        <select class="custom-select" name="active">
                            <option value="">-----</option>
                            <option value="0">None</option>
                            <option value="1">Active</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('role') }}</p>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('templates.admin.master') 
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">User</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit User</h6>
        </div>
        <div class="card-body">
            <div class="col-md">
                <div class="p-5">
                  <form class="user" method="post" action="{{ route('admin.user.update', $user->id)}}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                      <div class="col-sm-12 mb-3 ">
                          <label for="">Name</label>
                            <input type="text" name="name" class="form-control form-control-user" value="{{ $user->name}}">
                            <p class="text-danger">{{ $errors->first('name') }}</p>
                      </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-12 mb-3 ">
                            <label for="">Email</label>
                                <input type="text" name="email" class="form-control form-control-user" value="{{ $user->email}}">
                                <p class="text-danger">{{ $errors->first('email') }}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="">Role</label>
                        <select class="custom-select" name="role">
                            <option value="">-----</option>
                            <option {{$user->role == 0 ? 'selected' : ''}} value="0">User</option>
                            <option {{$user->role == 1 ? 'selected' : ''}} value="1">Admin</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('role') }}</p>
                    </div>
                    <div class="form-group">
                        <label for="">Active</label>
                        <select class="custom-select" name="active">
                            <option value="">-----</option>
                            <option {{$user->active == 0 ? 'selected' : ''}} value="0">None</option>
                            <option {{$user->active == 1 ? 'selected' : ''}} value="1">Active</option>
                        </select>
                        <p class="text-danger">{{ $errors->first('active') }}</p>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('templates.admin.master') @section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">User</h1>
    <a class="btn btn-success mb-2"  href="{{ route('admin.user.create') }}">Add User</a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All User</h6>
            @include('errors.success')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0"
                                role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-sort="ascending" aria-label="Name: activate to sort
                                            column descending" style="width: 20px;">
                                            Id
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Name
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Position:
                                            activate to sort column ascending" style="width: 246px;">
                                            Email
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Office:
                                            activate to sort column ascending" style="width: 50px;">
                                            Role
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                            colspan="1" aria-label="Age:
                                            activate to sort column ascending" style="width: 51px;">
                                            Active
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1"
                                        colspan="1" aria-label="Age:
                                        activate to sort column ascending" style="width: 90px;">
                                        Actions
                                    </th>
                                   
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $key => $item)
                                        <tr role="row" class="{{ $key %2 == 0 ? 'odd' : 'even'}}">
                                            <td class="sorting_1">{{ $item->id}}</td>
                                            <td>{{ $item->name}}</td>
                                            <td>{{ $item->email}}</td>
                                            <td>{{ $item->role == 1 ? 'Admin' : 'User' }}</td>
                                            <td id="active-{{ $item->id }}"> 
                                                @if ($item->active == 1)
                                                  <a href="javascript:void(0)" onclick="getActive({{$item->id}})" style="cursor: pointer"><i class="fas fa-check text-success"></i> </a>
                                                @else
                                                  <a href="javascript:void(0)" onclick="getActive({{$item->id}})" style="cursor: pointer"><i class="fas fa-times text-danger"></i></a>
                                                @endif
                                              </td>
                                            <td>
                                                <form action="{{ route('admin.user.destroy', $item->id)}}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a class="btn btn-danger" href="" data-toggle="modal" data-target="#modelId-{{ $item->id}}">Delete</a>
                                                    <a class="btn btn-primary" href="{{ route('admin.user.edit', $item->id)}}" role="button">Edit</a>
                                                    <!-- Modal -->
                                                    <div class="modal fade" id="modelId-{{ $item->id}}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title">Delete post</h5>
                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    Are you sure?
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                                
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    function getActive(id){
       $.ajax({
         url: "{{route('admin.user.active')}}",
         type: 'GET',
         cache: false,
         data: {
               id: id,
           },
         success: function(data){
           console.log('success')
           $('#active-'+id).html(data);
         },
         error: function() {
          alert("Có lỗi");
        }
      });
       return false;
     }
</script>
@endsection